import os

env=Environment(ENV=os.environ, CFLAGS='-g -pg', CXXFLAGS='-g -DDEBUG -pg', LINKFLAGS='-pg')
env.ParseConfig('pkg-config gtk+-3.0 sunpinyin-2.0 sqlite3 --cflags --libs')

env.Program('sunpinyin', source=['imi_gtkwin.cpp', 'sunpinyin.cpp'])

# -*- indent-tabs-mode: nil -*- vim:et:ts=4
