import os
Import('env')

env.Program('dict/mmseg', ['portability.o', 'slm/sim_dict.o', 'slm/sim_sen.o',
                      'slm/mmseg/mmseg.o'])

env.Program('dict/slmseg', ['portability.o', 'slm/sim_dict.o', 'slm/sim_sen.o',
                      'slm/slm.o', 'slm/slmseg/slmseg.o'])

env.Program('dict/ids2ngram', ['portability.o', 'slm/ids2ngram/ids2ngram.o'])

env.Program('dict/idngram_merge', ['portability.o', 'slm/ids2ngram/idngram_merge.o'])

env.Program('dict/slmbuild', ['portability.o', 'slm/sim_slmbuilder.o',
                         'slm/slmbuild/slmbuild.o'])

env.Program('dict/slmprune', ['portability.o', 'slm/sim_slm.o',
                         'slm/slmprune/slmprune.o'])

env.Program('dict/slminfo', ['portability.o', 'slm/slminfo/slminfo.o'])

env.Program('dict/slmthread', ['portability.o', 'slm/sim_slm.o',
                          'slm/thread/ValueCompress.o', 'slm/thread/slmthread.o'])

env.Program('dict/tslmendian', ['slm/tslmendian/slm_file.o',
                           'slm/tslmendian/slm_endian.o',
                           'slm/tslmendian/writer.o'])

env.Program('dict/tslminfo', ['portability.o', 'slm/slm.o', 'slm/tslminfo/tslminfo.o'])

env.Program('dict/tslmpack', ['portability.o', 'slm/slm.o',
                     	 'slm/thread/ValueCompress.o', 'slm/tslmpack/slmpack.o',
                     	 'slm/tslmpack/arpa_conv.o', 'slm/tslmpack/arpa_slm.o'])

env.Program('dict/genpyt', ['portability.o', 'slm/slm.o', 'slm/tslmendian/writer.o',
                   	   'common/lexicon/trie_writer.o', 'common/lexicon/gentrie.o',
                   	   'common/lexicon/trie_factory.o', 'common/lexicon/maker_factory.o',
                   	   'common/lexicon/trie.o', 'common/lexicon/trie_maker.o',
                   	   'common/lexicon/CUnitData.o',
                   	   'common/lexicon/tree/PNodeSet.o',
                   	   'common/lexicon/CUnigramSorter.o',
                       'xh/lexicon/CXhTrieMaker.o',
                       'xh/lexicon/path.o',
                       'xh/input/xh_data.o',
                       'pinyin/lexicon/pytrie_maker.o',
                   	   'pinyin/input/pinyin_data.o'])

env.Program('dict/getwordfreq', ['portability.o', 'slm/slm.o',
                            'slm/getwordfreq/getwordfreq.o'])

env.Program('dict/testvc', ['slm/thread/ValueCompress.o', 'slm/thread/test_vc.o'])

env.Substfile('sunpinyin-dictgen.mk.in', SUBST_DICT = {
    '@MAKE@': env['MAKE'],
    '@TAR@': env['TAR'],
    '@WGET@': env['WGET'],
    '@DATADIR@': env['DATADIR'],
    '@ENDIANNESS@': env['ENDIANNESS'],
    })
env.Command('dict/sunpinyin-dictgen', 'sunpinyin-dictgen.mk', [
        Copy("$TARGET", "$SOURCE"),
        Chmod("$TARGET", 0755),
    ])

# -*- indent-tabs-mode: nil -*- vim:et:ts=4
